spring:
  application:
    name: mcs-customers
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost:5433}/${DB_NAME:finance}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    open-in-view: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
server:
  port: ${SERVER_CUSTOMER_PORT:8083}
logging:
  level:
    com.castaneda: INFO
    org.springframework.web: WARN
    reactor.netty: WARN